name: Test Script Execution

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
    
    - name: Install sh
      run: sudo apt-get install -y bash


- name: Validate secrets
  run: |
    if [ -z "$FILE_TOKEN" ]; then echo "FILE_TOKEN is missing"; exit 1; fi
    if [ -z "$PROFILE_REPO" ]; then echo "PROFILE_REPO is missing"; exit 1; fi
    if [ -z "$BASE_URL" ]; then echo "BASE_URL is missing"; exit 1; fi
  env:
    FILE_TOKEN: ${{ secrets.FILE_TOKEN }}
    PROFILE_REPO: ${{ secrets.PROFILE_REPO }}
    BASE_URL: ${{ secrets.PATH }}

    
    - name: Run the script
      run: node run.js
