name: Test Script Execution

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Puppeteer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gconf-service \
          libasound2 \
          libatk1.0-0 \
          libcups2 \
          libdbus-1-3 \
          libx11-xcb1 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxrandr2 \
          libgbm1 \
          libgtk-3-0 \
          libpango-1.0-0 \
          libxss1 \
          libnss3 \
          libxshmfence1 \
          ca-certificates \
          fonts-liberation \
          libappindicator1 \
          libappindicator3-1 \
          libfontconfig1

    - name: Install dependencies
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      run: npm install

    - name: Debug environment variables
      run: env

    - name: Run the script
      env:
        FILE_TOKEN: ${{ secrets.FILE_TOKEN }}
        PROFILE_REPO: ${{ secrets.PROFILE_REPO }}
        PATH: ${{ secrets.PATH }}
      run: node run.js https://example.com

    - name: Debug npm logs
      if: failure()
      run: cat /home/runner/.npm/_logs/* || true
